###NumPy Arrays

In [2]:
import numpy as np 

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [10]:
arr = np.array(34)
arr.ndim

0

In [12]:
arr = np.array([1,2,3])
arr.ndim
arr.shape

(3,)

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim
arr.shape

(2, 3)

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.ndim
arr.shape

(3, 3)

In [22]:
# Range in NumPy insted of doing manually or using loops
range = np.arange(1,10,2) # start, stop, step
range

array([1, 3, 5, 7, 9])

In [21]:
arr = np.linspace(0,1,5) # start, stop, no. of values
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
# logarithmic scale array
arr = np.logspace(1, 3, 3) # 10^1 to 10^3, ...3 points
arr

array([  10.,  100., 1000.])

In [29]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [28]:
arr = np.zeros([2,3]) # rows, cols
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
arr = np.zeros([3,5], dtype = int) # rows, cols
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [34]:
arr = np.ones([2,3], dtype = int) # rows, cols
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
arr = np.full(5,10) # no. of value, default value
arr

array([10, 10, 10, 10, 10])

In [39]:
arr = np.full([2,4], 8.3) # [row, col], default value 
arr

array([[8.3, 8.3, 8.3, 8.3],
       [8.3, 8.3, 8.3, 8.3]])

In [41]:
arr = np.empty([2,3]) # Uninitialized array
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
arr = np.random.rand(5) # random floats(0 to 1)
arr

array([0.32049298, 0.70044431, 0.77153772, 0.64104146, 0.1142223 ])

In [44]:
arr = np.random.rand(2,3) # random floats(0 to 1)
arr

array([[0.85101046, 0.1714708 , 0.35754562],
       [0.46349414, 0.62938044, 0.15587146]])

In [47]:
arr = np.random.randn(2,3) # random floats from standarad normal distribution
arr # mean is 0 and S.D is 1

array([[-1.01799239, -0.19004747, -0.21183821],
       [-0.11572889, -1.31912232,  1.79615893]])

In [52]:
arr = np.random.randint(10,100) # starting, ending, size
arr

27

In [53]:
arr = np.random.randint(10,100,3) # starting, ending, size
arr

array([26, 84, 50], dtype=int32)

In [56]:
arr = np.random.randint(10,100,[3,4]) # starting, ending, dimenstion
arr

array([[79, 91, 56, 13],
       [51, 31, 30, 20],
       [57, 34, 69, 88]], dtype=int32)

## NumPy Data Types and Type Casting

In [61]:
arr = np.array([1,2,3.1,4,5]) # all the values in an array will same
arr # one float value 3.1 rest all the int value becomes float

array([1. , 2. , 3.1, 4. , 5. ])

In [16]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
lst = ["string", 1,2,5.6] # py list
#converting py list into np array
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [6]:
arr = np.array([1,2,34,4,5])
arr.dtype

dtype('int64')

In [11]:
arr = np.array([1,2,34,4,5], dtype = np.float32) # we can change the data type of an array
arr.dtype

dtype('float32')

In [17]:
arr = np.array([1,2,3.7,4,5], dtype = np.int32 )

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr

array([1, 2, 3, 4, 5], dtype=int32)

## Type Casting ----> astype()

In [20]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [22]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [23]:
new_arr.dtype

dtype('float64')

In [24]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

In [25]:
new_arr2.dtype

dtype('int64')

## Type Casting Errors

In [26]:
arr = np.array([1,2,"Hello"])
arr.dtype

dtype('<U21')

In [28]:
new_arr2 = arr.astype(np.int64) # it will give error 
new_arr2

ValueError: invalid literal for int() with base 10: np.str_('Hello')

## Array Reshaping --> Reshape, Ravel, Flatten

In [32]:
# Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
reshaped2 = reshaped.reshape(3,2)
reshaped2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
# ravel --> convert 1D array
ravel = reshaped2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [37]:
ravel[0] = 100 # Changes reflected into original array
ravel
reshaped2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [40]:
# flatten --> to 1D array
# return a copy of the array

flat = reshaped2.flatten()
flat

array([1, 2, 3, 4, 5, 6])

In [44]:
flat[0] = 455
flat

array([455,   2,   3,   4,   5,   6])

In [45]:
reshaped2

array([[1, 2],
       [3, 4],
       [5, 6]])

## Aritmetic Operators on Arrays

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [47]:
#additions
print(a+b)

[5 7 9]


In [49]:
#subtractions
print(a-b)
print(b-a)

[-3 -3 -3]
[3 3 3]


In [56]:
#divition
print(a/b)
#interger divitions
print(b//a)

[0.25 0.4  0.5 ]
[4 2 2]


In [54]:
#multiplications
print(a*b)

[ 4 10 18]


In [61]:
#modulus
print(b%a)

[0 1 0]


In [63]:
#exponet
print(a**2)
print(b**3)

[1 4 9]
[ 64 125 216]


## Universal Functions --> ufuncs

In [64]:
arr = np.array([1,4,9,16])

In [65]:
# square root --> np.sqrt()
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [67]:
# exponentioal -> np.exp -> e^x -> x is any integer
print(np.exp([1,2]))
print(np.exp(arr))

[2.71828183 7.3890561 ]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [68]:
#sine functions --> np.sin
angles = np.array([0, np.pi, np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


## indexing and slicing

In [69]:
a = [1,2,3,4,5]

In [71]:
a[-1:-4] # no output (no step)
a[-1:-4:-1] # start : end: step

[5, 4, 3]

In [73]:
a[ : : 2] # start: end: step

[1, 3, 5]

In [74]:
arr = np.array([10,20,30,40,50])
# indexes 0, 2, 4
arr[ 0:5:2]

array([10, 30, 50])

In [75]:
arr[-1]

np.int64(50)

### indeing and sclicing in multidimenstions array

In [76]:
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [78]:
# first 2 row of an array
print(matrix[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


In [83]:
# want 5,6 and 8,9
print(matrix[1:, 1:])

[[5 6]
 [8 9]]


### Index Arrays --> Advanced Indexing

In [84]:
#np.take --> built in func to perform indexing and sclicing
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [87]:
# Iterating with nditer()
arr = np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x, end = " ")

1 2 3 4 

In [88]:
# ndenumerate() -> both index + vlaue
for ind, x in np.ndenumerate(arr):
    print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


### views and copies

In [92]:
#views
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [97]:
view[0] = 200
view

array([200,   3])

In [98]:
arr

array([  1, 200,   3,   4,   5])

In [99]:
# copies
copy = arr[1:3].copy()
copy

array([200,   3])

In [100]:
copy[0] = 2
copy

array([2, 3])

In [101]:
arr

array([  1, 200,   3,   4,   5])

### Transpose

In [102]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [103]:
print(arr.transpose())

[[1 3]
 [2 4]]


### swapaxes --> swap 2 specific axes in a matrix.

In [106]:
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [107]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

### concatination

In [109]:
a = np.array([1,2])
b = np.array([3,4])

In [110]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

### vstack --> vertically stack 

In [113]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6],[7,8]])

In [117]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### hstack --> horizontally stack

In [118]:
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


### stack --> 0 -> row, 1 -> col

In [119]:
print(np.stack((arr1,arr2), axis = 0)) # row wise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
print(np.stack((arr1,arr2), axis = 1)) # col wise

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### spliting the arrays

In [126]:
arr =np.array ([[1,2],
        [3,4],
        [5,6],
        [7,8]])
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
print(np.split(arr, 4)) # splits only in equal parts

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


### Repeating

In [135]:
arr = np.array([1,2,3]) 
print(np.repeat(arr,3)) # reapting each element in an array

[1 1 1 2 2 2 3 3 3]


### Tile

In [136]:
print(np.tile(arr,3)) # reapte whole array

[1 2 3 1 2 3 1 2 3]


### Agregate Functions:

In [139]:
arr = np.array([1,2,3])

In [140]:
# sum
print(np.sum(arr)) # add of all element

6


In [141]:
# mean
print(np.mean(arr)) #[1,2,3] = sum / total no

2.0


In [143]:
# median
print(np.median(arr)) #[1,2,3] middle value

2.0


In [144]:
# std
print(np.std(arr)) #[1,2,3] how spread your numbers are

0.816496580927726


In [146]:
# variance
print(np.var(arr)) #[1,2,3] square of your std

0.6666666666666666


In [148]:
#min
print(np.min(arr)) #[1,2,3] minimum value

1


In [149]:
# max
print(np.max(arr)) #[1,2,3] maximum value

3


In [150]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
# sum only across col
print(np.sum(matrix, axis = 1))

[ 6 15 24]


In [153]:
# sum only across row
print(np.sum(matrix, axis = 0))

[12 15 18]


In [154]:
# sum only across col
print(np.median(matrix, axis = 1))

[2. 5. 8.]


In [155]:
# sum only across col
print(np.mean(matrix, axis = 1))

[2. 5. 8.]


In [156]:
# sum only across col
print(np.std(matrix, axis = 1))

[0.81649658 0.81649658 0.81649658]


In [157]:
# sum only across col
print(np.var(matrix, axis = 1))

[0.66666667 0.66666667 0.66666667]


### Cumulative Opeations

In [162]:
# running total (cumsum)
arr # array([1, 2, 3])
print(np.cumsum(arr)) # 1 -> 1, 1+2 -> 3, 3+3 -> 6
print(np.cumprod(arr)) # 1 -> 1, 1*2 -> 2, 2*3 -> 6

[1 3 6]
[1 2 6]


### Conditionam Based Choices

In [163]:
# Where:
arr

array([1, 2, 3])

In [164]:
result = np.where(arr < 2, "low", "high")
result

array(['low', 'high', 'high'], dtype='<U4')

In [167]:
#argwhere: row-column position for 2d arrays
arr = np.array([10,25,20,15,35,50])
arr

array([10, 25, 20, 15, 35, 50])

In [168]:
print(np.argwhere(arr>20))

[[1]
 [4]
 [5]]


In [179]:
mask = np.logical_or(arr>15, arr<35)
mask

array([ True,  True,  True,  True,  True,  True])

In [180]:
arr[mask]

array([10, 25, 20, 15, 35, 50])

In [181]:
mask = np.logical_and(arr>15, arr<35)
mask

array([False,  True,  True, False, False, False])

In [182]:
arr[mask]

array([25, 20])

In [174]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [186]:
new = np.array([0,1,5,0,5])
print(new)
print(np.nonzero(new))

[0 1 5 0 5]
(array([1, 2, 4]),)


### Broadcasting

In [189]:
# brodcating means streach the small array to match the size of a bigger array
# NumPy Compares the shapes of the arrays form the end (right to left)
    # if shape equal the are compatible
    # if one is 1, it can be streaches to match the other 
    # if shapes are different and not 1 or equal --> ERROR

In [196]:
img = np.array([[200, 150], [100, 250]])
img

array([[200, 150],
       [100, 250]])

In [195]:
bri = img + 50
bri

array([[250, 200],
       [150, 300]])

### Vectorization:

##### np.vectorize() -> convert a regular function to be applied on an array 

In [198]:
def square(x):
    return x*x

vfun = np.vectorize(square)

In [199]:
arr

array([10, 25, 20, 15, 35, 50])

In [200]:
print(vfun(arr))

[ 100  625  400  225 1225 2500]


### Dealing With Missing Vlaues

In [202]:
# np.nan --> not a number.
a = np.array([1, 2, np.nan, 4])
a

array([ 1.,  2., nan,  4.])

In [203]:
# np.inf and -np.inf -> positive and negative infinites

In [204]:
print(np.isnan(a))

[False False  True False]


In [210]:
b = np.array([1, 2, np.inf, np.nan, 10.2, ])

In [206]:
print(np.isinf(b))

[False False  True False]


In [211]:
print(np.logical_or(np.isinf(b), np.isnan(b)))

[False False  True  True False]


In [213]:
new_b = np.nan_to_num(b) # remove nan and infinite values 
new_b

array([1.00000000e+000, 2.00000000e+000, 1.79769313e+308, 0.00000000e+000,
       1.02000000e+001])